name: Build and export IPA

inputs:
  scheme:
    required: true
    type: string

  build_settings:
    required: true
    type: string

  platform:
    required: true
    type: string

runs:
  using: "composite"

  steps:
    - name: Build Archive
      env:
        scheme: ${{ inputs.scheme }}
        platform: ${{ inputs.platform }}
        build_settings: ${{ inputs.build_settings }}
      shell: bash
      run: |
        set -eo pipefail

        archive_file="build/$scheme.xcarchive"

        xcodebuild clean archive \
          -scheme "$scheme" \
          -archivePath "$archive_file" \
          -destination "generic/platform=$platform" \
          $build_settings

    - name: Create ExportOptions.plist
      id: export-options
      shell: bash
      run: |
        export_plist="$RUNNER_TEMP/ExportOptions.plist"

        echo "EXPORT_PLIST=$export_plist" >> $GITHUB_OUTPUT

        cat > "$export_plist" <<EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>development</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>compileBitcode</key>
            <false/>
        </dict>
        </plist>
        EOF

    - name: Export IPA
      env:
        scheme: ${{ inputs.scheme }}
        export_plist: ${{ steps.export-options.outputs.EXPORT_PLIST }}
      shell: bash
      run: |
        set -eo pipefail

        archive_file="build/$scheme.xcarchive"
        export_dir="build/$scheme"

        mkdir -p "$export_dir"

        xcodebuild \
          -exportArchive \
          -archivePath "$archive_file" \
          -exportPath "$export_dir" \
          -exportOptionsPlist "$export_plist"

        echo "IPA exported to: $export_dir"
        ls -lah "$export_dir"
