name: Build IPA

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        id: cache-dependencies
        with:
          path: ./Thirdparties
          key: ${{ runner.os }}-cache-${{ hashFiles('./bootstrap.sh') }}
          restore-keys: |
            ${{ runner.os }}-cache-

      - name: Bootstrap
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: ./bootstrap.sh
        shell: bash

      - name: Bump version
        env:
          build_number: ${{ github.run_number }}
        run: xcrun agvtool new-version -all $((47 + build_number))

      - name: Build IPA
        uses: ./.github/actions/build-archive-upload
        with:
          scheme: SwiftyYTDL
          build_settings: 'CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO ENABLE_BITCODE=NO'
          platform: iOS

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SwiftyYTDL-IPA
          path: build/SwiftyYTDL/*.ipa
