name: Xcode - Build and Analyze and Upload

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v4
        id: cache-dependecies
        with:
          path: ./Thirdparties
          key: ${{ runner.OS }}-cache-${{ hashFiles('./bootstrap.sh') }}
          restore-keys: |
            ${{ runner.OS }}-cache-

      - name: Bootstrap
        if: steps.cache-dependecies.outputs.cache-hit != 'true'
        run: ./bootstrap.sh
        shell: bash

      - name: Bump version
        env:
          build_number: ${{ github.run_number }}
        run: xcrun agvtool new-version -all $((47 + $build_number)) # temp fix

      - name: Build, acrhive and upload (SwiftyYTDL)
        uses: ./.github/actions/build-archive-upload
        with:
          scheme: SwiftyYTDL
          build_settings: 'ENABLE_BITCODE=YES'
          platform: ios
          auth_key_issuer_id: ${{ secrets.APPSTORE_ISSUER_ID }}
          auth_key_id: ${{ secrets.APPSTORE_API_KEY_ID }}
          auth_key_path: ${{ steps.appstore-private-key.outputs.AUTH_KEY_PATH }}
